import { useEffect, useMemo, useState, type ChangeEvent } from 'react'
import { detectWindowsArial } from './arialSignature'
import { generateLineBadgeSvg, type BadgeVersion } from './lineIdGenerators'
import { getShanghaiMetroPalette, parseLineNumber } from './lineIdUiShared'

type ThemeMode = 'light' | 'dark'

const themeStorageKey = 'site-theme'
const svgExportComment = '<!-- Generated by ShMetro Line ID Block Generator -->'
const initialPalette = getShanghaiMetroPalette(16) ?? {
  background: '#98D1C0',
  foreground: '#000000',
}

function getInitialThemeMode(): ThemeMode {
  if (typeof window === 'undefined') {
    return 'light'
  }

  const storedTheme = window.localStorage.getItem(themeStorageKey)

  if (storedTheme === 'light' || storedTheme === 'dark') {
    return storedTheme
  }

  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
}

function applyThemeMode(themeMode: ThemeMode) {
  document.documentElement.classList.toggle('dark', themeMode === 'dark')
  document.documentElement.style.colorScheme = themeMode
}

function isValidLineNumber(value: string) {
  return parseLineNumber(value) !== null
}

function downloadSvg(fileName: string, svgContent: string) {
  const blob = new Blob([`${svgExportComment}\n${svgContent}`], {
    type: 'image/svg+xml;charset=utf-8',
  })
  const objectUrl = window.URL.createObjectURL(blob)
  const downloadLink = document.createElement('a')

  downloadLink.href = objectUrl
  downloadLink.download = fileName
  document.body.append(downloadLink)
  downloadLink.click()
  downloadLink.remove()
  window.URL.revokeObjectURL(objectUrl)
}

function App() {
  const [themeMode, setThemeMode] = useState<ThemeMode>(() => getInitialThemeMode())
  const [version, setVersion] = useState<BadgeVersion>('2025')
  const [lineNumber, setLineNumber] = useState('16')
  const [badgeHeight, setBadgeHeight] = useState('100')
  const [useShanghaiMetroColors, setUseShanghaiMetroColors] = useState(true)
  const [foreground, setForeground] = useState(initialPalette.foreground)
  const [background, setBackground] = useState(initialPalette.background)
  const [hasArialFont, setHasArialFont] = useState(false)
  const [fontDetectionState, setFontDetectionState] = useState<'checking' | 'done'>('checking')

  const validLineNumber = isValidLineNumber(lineNumber)
  const validBadgeHeight = Number.isFinite(Number(badgeHeight)) && Number(badgeHeight) > 0
  const canGenerate = validLineNumber && validBadgeHeight

  useEffect(() => {
    applyThemeMode(themeMode)

    window.localStorage.setItem(themeStorageKey, themeMode)
  }, [themeMode])

  useEffect(() => {
    let cancelled = false

    void (async () => {
      const detected = await detectWindowsArial()

      if (!cancelled) {
        setHasArialFont(detected)
        setFontDetectionState('done')
      }
    })()

    return () => {
      cancelled = true
    }
  }, [])

  const previewSvg = useMemo(() => {
    if (!canGenerate) {
      return ''
    }

    return generateLineBadgeSvg({
      version,
      lineNumber,
      height: Number(badgeHeight),
      foreground,
      background,
    })
  }, [background, badgeHeight, canGenerate, foreground, lineNumber, version])

  const fileStem = validLineNumber ? `line-${lineNumber}-${version}` : `line-${version}`

  function handleThemeToggle() {
    setThemeMode((currentThemeMode) => (currentThemeMode === 'dark' ? 'light' : 'dark'))
  }

  function handleLineNumberChange(event: ChangeEvent<HTMLInputElement>) {
    const nextLineNumber = event.target.value.replace(/\D/g, '').slice(0, 2)
    setLineNumber(nextLineNumber)

    if (!useShanghaiMetroColors) {
      return
    }

    const palette = getShanghaiMetroPalette(nextLineNumber)

    if (!palette) {
      return
    }

    setForeground(palette.foreground)
    setBackground(palette.background)
  }

  function handleUseShanghaiMetroColorsChange(event: ChangeEvent<HTMLInputElement>) {
    const nextChecked = event.target.checked
    setUseShanghaiMetroColors(nextChecked)

    if (!nextChecked) {
      return
    }

    const palette = getShanghaiMetroPalette(lineNumber)

    if (!palette) {
      return
    }

    setForeground(palette.foreground)
    setBackground(palette.background)
  }

  function handleStandardDownload() {
    if (!previewSvg) {
      return
    }

    downloadSvg(`${fileStem}.svg`, previewSvg)
  }

  return (
    <main className="page-shell generator-page">
      <header className="page-header">
        <div className="page-meta-row">
          <p className="eyebrow">shmetro line id block generator</p>
          <button
            className="theme-toggle"
            type="button"
            onClick={handleThemeToggle}
            aria-label={themeMode === 'dark' ? '切换到浅色模式' : '切换到深色模式'}
          >
            {themeMode === 'dark' ? '切换到浅色模式' : '切换到深色模式'}
          </button>
        </div>
        <h1>上海地铁线路号方块生成器</h1>
        <p className="lead">生成并导出上海地铁风格线路号方块 SVG。</p>
        <div className="docs-callout">
          <strong>关于本页</strong>
          <p>支持切换 2020 / 2025 两套参数，并导出标准 SVG。</p>
        </div>
        <div className="inline-links" aria-label="外部链接">
          <a href="https://github.com/Unnamed2964/kyuri-shmetro-line-id-block-generator" target="_blank" rel="noreferrer">
            旧版 GitHub 仓库
          </a>
          <a href="https://github.com/Unnamed2964" target="_blank" rel="noreferrer">
            GitHub 主页
          </a>
          <a href="https://umamichi.moe/" target="_blank" rel="noreferrer">
            作者博客
          </a>
        </div>
      </header>

      <section className="panel">
        <h2>字体检测</h2>
        <p className="panel-subtitle">
          使用 Canvas 字形宽度签名检查系统 Arial 是否存在，避免预览在不同设备上静默回退。
        </p>
        <p className="font-detection-summary">
          {fontDetectionState === 'checking'
            ? '正在测量 Arial。'
            : hasArialFont
              ? '系统 Arial 已检测到。'
              : '系统 Arial 未通过签名校验。'}
        </p>
        <div className="font-detection-list" role="list" aria-label="字体检测结果">
          <article className="font-detection-card" role="listitem">
            <div className="font-detection-header">
              <strong>Arial</strong>
              <span className={`status-pill ${fontDetectionState === 'checking' ? 'pending' : hasArialFont ? 'success' : 'warning'}`}>
                {fontDetectionState === 'checking' ? '检测中' : hasArialFont ? '已检测到' : '未检测到'}
              </span>
            </div>
          </article>
        </div>
      </section>

      <section className="panel">
        <h2>生成设置</h2>
        <div className="form-grid single-column">
          <label className="field-label" htmlFor="version-select">
            <span>版本</span>
            <select
              id="version-select"
              value={version}
              onChange={(event) => setVersion(event.target.value as BadgeVersion)}
            >
              <option value="2020">2020</option>
              <option value="2025">2025</option>
            </select>
          </label>

            <label className="field-label" htmlFor="line-number-input">
              <span>线路号码</span>
            <input
              id="line-number-input"
              className="text-input"
              type="text"
              inputMode="numeric"
              maxLength={2}
                placeholder="例如：0、10、16、99（支持 0~99）"
              value={lineNumber}
              onChange={handleLineNumberChange}
              aria-invalid={lineNumber ? !validLineNumber : undefined}
            />
          </label>

            <label className="field-label" htmlFor="badge-height-input">
              <span>高度</span>
              <input
                id="badge-height-input"
                className="text-input"
                type="number"
                min="1"
                step="1"
                value={badgeHeight}
                onChange={(event) => setBadgeHeight(event.target.value)}
                aria-invalid={badgeHeight ? !validBadgeHeight : undefined}
              />
            </label>

          <label className="checkbox-row">
            <input
              type="checkbox"
              checked={useShanghaiMetroColors}
              onChange={handleUseShanghaiMetroColorsChange}
            />
            <span>自动填充上海地铁标准色号</span>
          </label>

          <div className="field-row">
            <label className="field-label" htmlFor="foreground-color-input">
              <span>前景色</span>
              <input
                id="foreground-color-input"
                type="color"
                value={foreground}
                onChange={(event) => setForeground(event.target.value)}
                disabled={useShanghaiMetroColors}
              />
            </label>
            <label className="field-label" htmlFor="background-color-input">
              <span>背景色</span>
              <input
                id="background-color-input"
                type="color"
                value={background}
                onChange={(event) => setBackground(event.target.value)}
                disabled={useShanghaiMetroColors}
              />
            </label>
          </div>
        </div>
      </section>

      <section className="panel result-panel">
        <h2>结果</h2>
        <div className="result-block">
          <div className="badge-preview">
            <div className={`preview-canvas${previewSvg ? ' has-svg' : ''}`}>
              {previewSvg ? <div dangerouslySetInnerHTML={{ __html: previewSvg }} /> : '输入线路号码即可预览效果。'}
            </div>
          </div>
          <div className="result-actions">
            <button className="secondary-button" type="button" onClick={handleStandardDownload} disabled={!canGenerate}>
              下载 SVG
            </button>
          </div>
        </div>
      </section>

      <section className="panel notes-section" aria-labelledby="notes-title">
        <h2 id="notes-title">说明</h2>
        <p>
          本工具的设计参数基于对实拍照片与 SVG 资料的视觉反推，不代表上海申通地铁集团有限公司的任何企业视觉标准或官方规范。
        </p>
        <p>输出结果仅供个人学习、参考及非商业用途，请勿将其用于任何官方或商业场合。</p>
      </section>
    </main>
  )
}

export default App
