import { useRef, useState, type ChangeEvent } from 'react'
import LineIdBadge from './components/lineIdBadge'

const SHMETRO_LINE_COLORS: Record<number, string> = {
  1: '#E3002B',
  2: '#8CC220',
  3: '#FCD600',
  4: '#461D84',
  5: '#944D9A',
  6: '#D40068',
  7: '#ED6F00',
  8: '#0094D8',
  9: '#87CAED',
  10: '#C6AFD4',
  11: '#871C2B',
  12: '#007B61',
  13: '#E999C0',
  14: '#626020',
  15: '#BCA886',
  16: '#98D1C0',
  17: '#BC796F',
  18: '#C4984F',
  19: '#F5AB78',
  20: '#009F65',
  21: '#F7AF00',
  22: '#5F376F',
  23: '#B0D478',
}

const SHMETRO_WHITE_TEXT_LINES = new Set([1, 4, 5, 6, 8, 11, 12, 14, 17, 20, 22])

function getShanghaiMetroPalette(lineId: number) {
  const background = SHMETRO_LINE_COLORS[lineId]

  if (!background) {
    return null
  }

  return {
    background,
    foreground: SHMETRO_WHITE_TEXT_LINES.has(lineId) ? '#ffffff' : '#000000',
  }
}

function App() {
  const [lineId, setLineId] = useState(16)
  const [foreground, setForeground] = useState('#000000')
  const [background, setBackground] = useState('#98D1C0')
  const [useShanghaiMetroColors, setUseShanghaiMetroColors] = useState(true)

  const badgeSvgRef = useRef<SVGSVGElement>(null)
  const svgExportComment = '<!-- Generated by ShMetro Line ID Block Generator -->'
  const fileName = `line-${lineId}-badge.svg`

  const standardPalette = getShanghaiMetroPalette(lineId)
  const isValidLineId = Number.isInteger(lineId) && lineId >= 0 && lineId < 100

  const applyShanghaiMetroPalette = (nextLineId: number) => {
    const palette = getShanghaiMetroPalette(nextLineId)

    if (!palette) {
      return
    }

    setForeground(palette.foreground)
    setBackground(palette.background)
  }

  const handleLineIdChange = (event: ChangeEvent<HTMLInputElement>) => {
    const nextLineId = Number(event.target.value)
    setLineId(nextLineId)

    if (useShanghaiMetroColors) {
      applyShanghaiMetroPalette(nextLineId)
    }
  }

  const handleUseShanghaiMetroColorsChange = (event: ChangeEvent<HTMLInputElement>) => {
    const checked = event.target.checked
    setUseShanghaiMetroColors(checked)

    if (checked) {
      applyShanghaiMetroPalette(lineId)
    }
  }

  const handleDownload = () => {
    const svgElement = badgeSvgRef.current

    if (!svgElement) {
      return
    }

    const serializer = new XMLSerializer()
    const svgMarkup = `${svgExportComment}\n${serializer.serializeToString(svgElement)}`
    const svgBlob = new Blob([svgMarkup], { type: 'image/svg+xml;charset=utf-8' })
    const objectUrl = window.URL.createObjectURL(svgBlob)
    const downloadLink = document.createElement('a')

    downloadLink.href = objectUrl
    downloadLink.download = fileName
    document.body.append(downloadLink)
    downloadLink.click()
    downloadLink.remove()
    window.URL.revokeObjectURL(objectUrl)
  }

  return (
    <main className="page-shell generator-page">
      <header className="page-header">
        <p className="eyebrow">ShMetro</p>
        <h1>Line ID Block Generator</h1>
        <p className="lead">
          生成上海地铁线路编号 SVG 色块，支持自动套用标准线路色，或手动微调前景与背景颜色。
        </p>
      </header>
      <section className="panel">
        <h2>生成设置</h2>
        <div className="form-grid single-column">
          <label className="field-block">
            <span>Line ID</span>
            <input type="number" value={lineId} onChange={handleLineIdChange} />
          </label>
          <label className="checkbox-row">
            <input
              type="checkbox"
              checked={useShanghaiMetroColors}
              onChange={handleUseShanghaiMetroColorsChange}
            />
            <span>自动填充上海地铁标准色号</span>
          </label>
          <label className="field-block">
            <span>Foreground Color</span>
            <input
              type="color"
              value={foreground}
              onChange={(e) => setForeground(e.target.value)}
              disabled={useShanghaiMetroColors}
            />
          </label>
          <label className="field-block">
            <span>Background Color</span>
            <input
              type="color"
              value={background}
              onChange={(e) => setBackground(e.target.value)}
              disabled={useShanghaiMetroColors}
            />
          </label>
          {useShanghaiMetroColors && (
            <p className="toolbar-hint color-hint">
              {standardPalette
                ? `已按上海地铁 ${lineId} 号线标准色自动填充。`
                : '当前线路暂无内置标准色号，保留现有配色。'}
            </p>
          )}
        </div>
      </section>
      <section className="panel">
        <h2>Line ID: {lineId}</h2>

        <p className="panel-subtitle">预览当前色块，并导出 SVG 文件。</p>
        <div className="preview-canvas badge-preview">
          {isValidLineId ? (
            <LineIdBadge
              ref={badgeSvgRef}
              lineId={lineId}
              foreground={foreground}
              background={background}
            />
          ) : (
            <p className="toolbar-hint">Line ID 需在 0 到 99 之间。</p>
          )}
        </div>
        <div className="result-actions">
          <button className="secondary-button" onClick={handleDownload} disabled={!isValidLineId}>
            下载 SVG
          </button>
        </div>
      </section>
    </main>
  )
}

export default App
